### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [Sieniawski/8.9#1]
- [x] niepotrzebny enter w 2. linijce
- [x] brak średnika po wywołaniu funkcji `console.log` oraz `makeTree`
- [x] zakomentowany kod

**Comment by wsieniawski** [comment]
done

**Comment by kacgrzes** [comment]
Wyślij mi linka na platformie żebym wiedział do którego zadania w panelu mam się odnieść. Na przyszłość oczywiście prosiłbym o to samo. Dzięki!
